import dayjs from 'dayjs';
import calendar from 'dayjs/plugin/calendar';
import LocalizedFormat from 'dayjs/plugin/LocalizedFormat';
import duration from 'dayjs/plugin/Duration';
import Weekday from 'dayjs/plugin/Weekday';
import advancedFormat from 'dayjs/plugin/advancedFormat';
import weekYear from 'dayjs/plugin/weekYear';
import weekOfYear from 'dayjs/plugin/weekOfYear';
import localeData from 'dayjs/plugin/localeData';
import MinMax from 'dayjs/plugin/minMax';
import DayOfYear from 'dayjs/plugin/dayOfYear';
import isBetween from 'dayjs/plugin/isBetween';
import objectSupport from 'dayjs/plugin/objectSupport';
import utc from 'dayjs/plugin/utc';
import isToday from 'dayjs/plugin/isToday';

import 'dayjs/locale/fr';
dayjs.locale('fr');
dayjs.extend(calendar);
dayjs.extend(weekYear);
dayjs.extend(weekOfYear);
dayjs.extend(Weekday);
dayjs.extend(LocalizedFormat);
dayjs.extend(duration);
dayjs.extend(advancedFormat);
dayjs.extend(localeData);
dayjs.extend(MinMax);
dayjs.extend(DayOfYear);
dayjs.extend(isBetween);
dayjs.extend(objectSupport);
dayjs.extend(utc);
dayjs.extend(isToday);
export default dayjs;
